import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { twJoin } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={twJoin(
          inter.className,
          "h-screen mx-auto max-w-screen-lg px-4 bg-gradient-to-b from-blue-50 to-red-50 bg-no-repeat"
        )}
      >
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
